// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var AIPlayer$Game_new = require("./AIPlayer.bs.js");
var Connect4$Game_new = require("./Connect4.bs.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var HumanPlayer$Game_new = require("./HumanPlayer.bs.js");

function Referee(MyGame, Player1, Player2) {
  var playGame = function (param) {
    try {
      var _s = Curry._1(MyGame.initialState, "5 7");
      while(true) {
        var s = _s;
        console.log(Curry._1(MyGame.stringOfState, s));
        var player = Curry._1(MyGame.gameStatus, s);
        if (typeof player === "number") {
          console.log("Draw...");
          return ;
        }
        if (player.TAG === /* Win */0) {
          console.log(Curry._1(MyGame.stringOfPlayer, player._0) + " wins!");
          return ;
        }
        var player$1 = player._0;
        console.log(Curry._1(MyGame.stringOfPlayer, player$1) + "'s turn.");
        var theMove = player$1 ? Curry._1(Player2.nextMove, s) : Curry._1(Player1.nextMove, s);
        console.log(Curry._1(MyGame.stringOfPlayer, player$1) + (" makes the move " + Curry._1(MyGame.stringOfMove, theMove)));
        _s = Curry._2(MyGame.nextState, s, theMove);
        continue ;
      };
    }
    catch (raw_message){
      var message = Caml_js_exceptions.internalToOCamlException(raw_message);
      if (message.RE_EXN_ID === "Failure") {
        console.log(message._1);
        return ;
      }
      throw message;
    }
  };
  return {
          CurrentGame: MyGame,
          playGame: playGame
        };
}

var $$let = HumanPlayer$Game_new.HumanPlayer(Connect4$Game_new.Connect4);

var partial_arg_nextMove = $$let.nextMove;

var partial_arg = Connect4$Game_new.Connect4;

var $$let$1 = AIPlayer$Game_new.AIPlayer(Connect4$Game_new.Connect4);

var R1 = (function (param) {
      var playGame = function (param$1) {
        try {
          var _s = Curry._1(partial_arg.initialState, "5 7");
          while(true) {
            var s = _s;
            console.log(Curry._1(partial_arg.stringOfState, s));
            var player = Curry._1(partial_arg.gameStatus, s);
            if (typeof player === "number") {
              console.log("Draw...");
              return ;
            }
            if (player.TAG === /* Win */0) {
              console.log(Curry._1(partial_arg.stringOfPlayer, player._0) + " wins!");
              return ;
            }
            var player$1 = player._0;
            console.log(Curry._1(partial_arg.stringOfPlayer, player$1) + "'s turn.");
            var theMove = player$1 ? Curry._1(param.nextMove, s) : Curry._1(partial_arg_nextMove, s);
            console.log(Curry._1(partial_arg.stringOfPlayer, player$1) + (" makes the move " + Curry._1(partial_arg.stringOfMove, theMove)));
            _s = Curry._2(partial_arg.nextState, s, theMove);
            continue ;
          };
        }
        catch (raw_message){
          var message = Caml_js_exceptions.internalToOCamlException(raw_message);
          if (message.RE_EXN_ID === "Failure") {
            console.log(message._1);
            return ;
          }
          throw message;
        }
      };
      return {
              CurrentGame: partial_arg,
              playGame: playGame
            };
    })({
      PlayerGame: $$let$1.PlayerGame,
      nextMove: $$let$1.nextMove,
      playerName: $$let$1.playerName
    });

var $$let$2 = HumanPlayer$Game_new.HumanPlayer(Connect4$Game_new.Connect4);

var partial_arg_nextMove$1 = $$let$2.nextMove;

var partial_arg$1 = Connect4$Game_new.Connect4;

var $$let$3 = HumanPlayer$Game_new.HumanPlayer(Connect4$Game_new.Connect4);

var R2 = (function (param) {
      var playGame = function (param$1) {
        try {
          var _s = Curry._1(partial_arg$1.initialState, "5 7");
          while(true) {
            var s = _s;
            console.log(Curry._1(partial_arg$1.stringOfState, s));
            var player = Curry._1(partial_arg$1.gameStatus, s);
            if (typeof player === "number") {
              console.log("Draw...");
              return ;
            }
            if (player.TAG === /* Win */0) {
              console.log(Curry._1(partial_arg$1.stringOfPlayer, player._0) + " wins!");
              return ;
            }
            var player$1 = player._0;
            console.log(Curry._1(partial_arg$1.stringOfPlayer, player$1) + "'s turn.");
            var theMove = player$1 ? Curry._1(param.nextMove, s) : Curry._1(partial_arg_nextMove$1, s);
            console.log(Curry._1(partial_arg$1.stringOfPlayer, player$1) + (" makes the move " + Curry._1(partial_arg$1.stringOfMove, theMove)));
            _s = Curry._2(partial_arg$1.nextState, s, theMove);
            continue ;
          };
        }
        catch (raw_message){
          var message = Caml_js_exceptions.internalToOCamlException(raw_message);
          if (message.RE_EXN_ID === "Failure") {
            console.log(message._1);
            return ;
          }
          throw message;
        }
      };
      return {
              CurrentGame: partial_arg$1,
              playGame: playGame
            };
    })({
      PlayerGame: $$let$3.PlayerGame,
      nextMove: $$let$3.nextMove,
      playerName: $$let$3.playerName
    });

Curry._1(R1.playGame, undefined);

exports.Referee = Referee;
exports.R1 = R1;
exports.R2 = R2;
/* R1 Not a pure module */
